version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: chapters-mongodb-test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chapters

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: chapters-app-test
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USE_SOCKET_MODE=true
      - MONGODB_URI=mongodb://mongodb:27017/chapters
      - PHASE_TEST_MODE=true
    depends_on:
      - mongodb
    command: npx nodemon --exec ts-node src/index.ts

volumes:
  mongodb_test_data:
